### ISSUE TITLE
Add link to this repo in Chrome Web Store

### ISSUE THREAD

**Issue by cmj2002** [yuedanlabs/icp-query-extension#11]
I suggest adding a link to this repo on the page in Chrome Web Store (similar to [OpenAI Translator](https://chrome.google.com/webstore/detail/openai-translator/ogjibjphoadhljaoicdnjnmgokohngcc)). On the one hand, it makes it easier for users to provide feedback and contribute. On the other hand, it can attract users who are fond of open-source products.

I have been using this extension for a long time, but I didn't even know it was open-source until it appeared on my GitHub Feeds today.

**Comment by yuedanlabs** [comment]
Thank you for your suggestion

In the next version, we will consider putting our open source project link in the appropriate place

Thank you very much for your support of our work, and your valuable suggestions and opinions on our project are also very welcome

**Comment by yuedanlabs** [comment]
@cmj2002
