### ISSUE TITLE
Hello, which website does the data source come from? Is the accuracy of the data source reliable

### ISSUE THREAD

**Issue by wujunze** [yuedanlabs/icp-query-extension#12]
Hello
		Which website does the data source come from? Is the accuracy of the data source reliable ?

Thanks

**Comment by yuedanlabs** [comment]
Except for the official website where the data is generated, all other websites are unreliable and cannot guarantee the accuracy of the data

We just provide some convenient reference data, not the official website of the data, so no guarantee can be given here.

But you can do a reasonable verification against other data sources, and then decide whether to adopt

**Comment by yuedanlabs** [comment]
Thanks for using, and welcome to put forward more valuable suggestions.
