### ISSUE TITLE
api受限了

### ISSUE THREAD

**Issue by huangsijun17** [yuedanlabs/icp-query-extension#16]
> https://phehmt.laf.run/icp?token=637e79b77fd9b2915dfb7e6c

```
{
    "code": 200,
    "msg": "limited(too much has been used today, please use again tomorrow, or contact us)"
}
```

**Comment by luojianxhlxt** [comment]
申请的token也是报这个

**Comment by cikichen** [comment]
一样

**Comment by liansong2011** [comment]
同报，不知道有什么解决办法吗

**Comment by hqzh** [comment]
icp服务器受到攻击啦

**Comment by lly-ke** [comment]
@yuedanlabs 能自建的方式或者用第三方收费api吗

**Comment by yuedanlabs** [comment]
首先为这几天的不稳定说句抱歉，一方面是所使用服务器厂商近期升级有部分小变动影响，没有及时调整（目前已解决）。另一方面是受到了较为量大的攻击。

长期以来，都受到不同程度的攻击， 但是近期尤其多且量大，有些是滥用的 所以限制一直在逐步提高。

我们一开始的目标是坚持最大程度的方便用户使用，尤其是日常的无感使用，不必为了一个本该免费的基础信息而付出额外的花费 ，但目前看来现实好像还是那么的不如意。

如果没有这些攻击行为，服务器是非常稳定可靠且省心， 我们虽未有任何收入，但也完全可以覆盖小成本的支出，这是我们的初心，也是这个工具开放给大家用的初心。

关于自建和使用第三方api，这个工具一直都可以，在首页文档从一开始就公布了最新版本所使用的api接口数据结构的定义。任何第三方api只要满足这个数据结构，均可在配置页面使用，要具体了解详情请看 [#about-the-api](https://github.com/yuedanlabs/icp-query-extension#about-the-api)

如果用户能够接受一定程度合理的付费，我们近期可以考虑增加付费方案，以提供更为稳定的专有服务和满足更高的需求。

如果有什么诉求或者建议，也非常欢迎讨论或者反馈

---
First of all, I would like to apologize for the instability in the past few days. On the one hand, the server manufacturer used has been affected by some minor changes in recent upgrades and has not been adjusted in time (it has been resolved now). On the other hand, it has received a relatively large amount of attacks.

For a long time, they have been attacked to varying degrees, but recently they have been particularly numerous and large, and some are abused, so restrictions have been gradually increased.

Our initial goal was to maximize user convenience, especially for daily use without having to pay extra for basic information that should be free. However, it seems that the reality is still so unsatisfactory.

Without these attacks, the server would be very stable, reliable and worry-free. Although we do not have any income, we can still cover the small cost of expenditure. This is our original intention and the original intention of opening this tool to everyone.

Regarding self-building and using third-party APIs, this tool has always been possible. The definition of the API interface data structure used in the latest version has been announced from the beginning in the homepage document. Any third-party API can be used on the configuration page as long as it meets this data structure. For details, please see [#about-the-api](https://github.com/yuedanlabs/icp-query-extension#about-the-api)

If users can accept a certain level of reasonable payment, we may consider adding payment plans in the near future to provide more stable proprietary services and meet higher needs.

If you have any demands or suggestions, discussion or feedback is very welcome.

**Comment by yuedanlabs** [comment]
另外，请保持在浏览器插件中查阅您所需要的信息，任何疑是不合理的api使用方式超过我们的容忍度时都会被自动拦截且临时或永久受限。

另外 我们近期会保持更新以提高用户的使用体验。

---
In addition, please keep checking the browser plug-in for the information you need. Any suspected unreasonable API usage that exceeds our tolerance will be automatically blocked and temporarily or permanently restricted.

In addition, we will keep updating in the near future to improve user experience.

**Comment by lly-ke** [comment]
@yuedanlabs 暂时没有第三方api满足这种响应数据格式吧, 我找了几个数据格式都对不上. 

我感觉大部分用户可以接受付费

**Comment by yuedanlabs** [comment]
> @yuedanlabs 暂时没有第三方api满足这种响应数据格式吧, 我找了几个数据格式都对不上.

每个应用都会有自己方便的格式 这个没办法去适配

> 我感觉大部分用户可以接受付费

我们近期考虑提供一种可选方案来满足这种需求

感谢使用 并提供宝贵的意见

**Comment by liliang13** [comment]
> > @yuedanlabs 暂时没有第三方api满足这种响应数据格式吧, 我找了几个数据格式都对不上.
> 
> 每个应用都会有自己方便的格式 这个没办法去适配
> 
> > 我感觉大部分用户可以接受付费
> 
> 我们近期考虑提供一种可选方案来满足这种需求
> 
> 感谢使用 并提供宝贵的意见

+1
希望提供更稳定的可选方案

**Comment by yuedanlabs** [comment]
不好意思久等了，首先预祝大家新年快乐

稍后会推出更新内容，包括新的api、现有遗留问题、功能更新和一些小功能

我们2024见

**Comment by liliang13** [comment]
> 不好意思久等了，首先预祝大家新年快乐
> 
> 稍后会推出更新内容，包括新的api、现有遗留问题、功能更新和一些小功能
> 
> 我们2024见

Hello 

目前进展如何了呢
