### ISSUE TITLE
一些域名无法显示备案信息

### ISSUE THREAD

**Issue by liliang13** [yuedanlabs/icp-query-extension#17]
一些国内显然有备案的域名，均无法显示备案信息，提示No licenses found.

例如:szbus.com.cn,jtt.sc.gov.cn等等。原生token与自己申请的token均一样。

怀疑是否还是api问题？

**Comment by yuedanlabs** [comment]
@liliang13 是的，近期改善。

另外虽说所有token查询的结果没有区别，但建议请尽量使用自己所申请的token。
