### ISSUE TITLE
城市二级域名兼容性有问题？

### ISSUE THREAD

**Issue by huangsijun17** [yuedanlabs/icp-query-extension#20]
下列域名有ICP备案，但插件内显示没有。
> library.sh.cn
> e.mail.sh.cn
> online.sh.cn

**Comment by yuedanlabs** [comment]
验证是有数据的，应该是域名规则有些问题，我来修复一下

**Comment by yuedanlabs** [comment]
已修复 @huangsijun17 

感谢～
