### ISSUE TITLE
提示 No licenses found.

### ISSUE THREAD

**Issue by lifesign** [yuedanlabs/icp-query-extension#3]
这个可能是什么原因，看了下配置页面的 api 地址，请求的是 https://phehmt.laf.run/icp

**Comment by yuedanlabs** [comment]
可能三种原因：
1. 要查询的域名本身未备案
2. 地处非中国地区，网络问题
3. 网络请求失败

建议打开 www.baidu.com 然后看是否查询成功且显示正确，若正确，则问题 1，否则考虑 2和3

感谢反馈
