### ISSUE TITLE
推荐一个相似的项目Domain Admin基于Python3 + Vue3.js 技术栈实现的域名和SSL证书监测平台

### ISSUE THREAD

**Issue by mouday** [yuedanlabs/icp-query-extension#4]
基于Python3 + Vue3.js 技术栈实现的域名和SSL证书监测平台

用于解决，不同业务域名SSL证书，申请自不同的平台，到期后不能及时收到通知，导致线上访问异常，被老板责骂的问题

核心功能：域名 和SSL证书 的过期监控，到期提醒

支持证书：单域名证书、多域名证书、通配符证书、IP证书、自签名证书

证书部署： 单一主机部署、多主机部署、动态主机部署

通知渠道：支持邮件、Webhook、企业微信、钉钉、飞书等通知方式

支持平台：macOS、Linux、Windows

同时，Domain Admin也是一个轻量级监控方案，占用系统资源较少，安装包仅1.5 MB

项目截图

![](https://user-images.githubusercontent.com/24365682/247851802-c6d81774-159c-4193-bd77-909f8bfdf719.png)

预览地址：https://mouday.github.io/domain-admin-web/

账号密码随意，预览模式仅提供模拟数据，无法操作修改

**Comment by mouday** [comment]
是优势，也是缺点，需要独立部署

**Comment by yuedanlabs** [comment]
thx
